{{- $rbac := .Values.rbac | default dict }}
{{- if or (eq $rbac.enabled true ) (eq $rbac.enabled nil ) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ccm-linode
  namespace: {{ required ".Values.namespace required" .Values.namespace }}
{{- end }}