name: 'Auto Merge GH-Pages'

on:
  push:
    branches:
        - main

jobs:
  merge-main-to-gh-pages:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Full clone necessary for proper merge

    - name: Set git config
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "Github Actions"
    
    - name: Merge main into gh-pages
      run: |
        git checkout gh-pages
        git pull
        git merge --no-ff main -m "Automatically merge main into gh-pages"
        git push